# Copyright 2022 Cartesi Pte. Ltd.
#
# SPDX-License-Identifier: Apache-2.0
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use
# this file except in compliance with the License. You may obtain a copy of the
# License at http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed
# under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
# CONDITIONS OF ANY KIND, either express or implied. See the License for the
# specific language governing permissions and limitations under the License.

import json
import requests
from os import environ
from abc import ABC, abstractmethod
from coil_wallet.util import str_to_hex, encode_values, encode_function_call
from typing import List, Tuple, Any

def encode(d):
    return "0x" + d.encode("utf-8").hex()

class Output(ABC):
    """
    Base class representing a result generated by processing an input.

    It is resposible for converting its payload to the format expected by
    Cartesi rollups.

        Parameters:
            payload(str): the actual data generated after processing the input
    """

    def __init__(self, payload: str):
        self.endpoint = "/output"
        if payload[:2] == "0x":
            self.payload = payload
        else:
            self.payload = "0x" + payload
    
    @classmethod
    def from_hex(cls, hex_value:str):
        return cls(hex_value)

    def create(self, rollup_server_address=None):
        rollup_server = "http://localhost:5004"
        if "ROLLUP_HTTP_SERVER_URL" in environ:
            rollup_server = environ["ROLLUP_HTTP_SERVER_URL"]
        if rollup_server_address is not None:
            rollup_server = rollup_server_address

        return requests.post(rollup_server + self.endpoint, json={"payload": self.payload})
    


class Voucher(Output):
    """
    A Voucher is an `Output` representing a transaction
    that can be carried out on the base layer blockchain,
    such as a transfer of assets.

        Parameters:
            destination(str): destination of the contract who will execute the payload
            payload(bytes): an ABI encoded contract function call
    """

    def __init__(self, destination: str, payload: bytes|str, value = None):
        self.endpoint = "/voucher"
        self.destination = destination
        self.value = value

        if value is None:
            self.value = '0x' + encode_values(["uint256"], [0]).hex()

        if payload[:2] == "0x":
            super().__init__(payload)
        else:        
            hexpayload = "0x" + payload.hex()
            super().__init__(hexpayload)
    
    @classmethod
    def from_hex(cls, destination:str, hex_value:str, value:int=None):
        return cls(destination, hex_value, value)

    @classmethod
    def from_function_selector(cls, destination:str, selector:str, types:List[str], values:List[int]):
        transfer_payload = encode_function_call(selector, types, values)
        return cls(destination, transfer_payload)

    def create(self, rollup_server_address=None):
        rollup_server = "http://localhost:5004"
        if "ROLLUP_HTTP_SERVER_URL" in environ:
            rollup_server = environ["ROLLUP_HTTP_SERVER_URL"]
        if rollup_server_address is not None:
            rollup_server = rollup_server_address

        return requests.post(rollup_server + "/voucher", json={"payload": self.payload, "destination": self.destination, "value": self.value})


class Notice(Output):
    """
    A Notice is an `Output` representing an informational statement
    that can be validated in the base layer blockchain.

        Parameters:
            payload(str): a string containing arbitrary data
    """

    def __init__(self, payload: str):
        super().__init__(payload)
        self.endpoint = "/notice"

    @classmethod
    def from_json(cls, json_object):
        if (isinstance(json_object, str)):
            return cls.from_string(json_object)
        
        j_string = json.dumps(json_object)
        return cls.from_string(j_string)
    
    @classmethod
    def from_string(cls, string:str):
        hex_encoded = encode(string)
        return cls(hex_encoded)



class Report(Output):
    """
    A Report is an `Output` representing an application log.

        Parameters:
            payload(str): a string containing arbitrary data
    """

    def __init__(self, payload: str):
        super().__init__(payload)
        self.endpoint = "/report"

    @classmethod
    def from_json(cls, json_object):
        if (isinstance(json_object, str)):
            return cls.from_string(json_object)
        
        j_string = json.dumps(json_object)
        return cls.from_string(j_string)
    
    @classmethod
    def from_string(cls, string:str):
        hex_encoded = encode(string)
        return cls(hex_encoded)

class Error(Output):
    """
    An Error is an `Output` representing that an error has ocurred
    during the processing of an input.

    If something unexpected such as an exception or error occurs during
    the processing of an input, that input must be rejected.

        Parameters:
            payload(str): a string containing arbitrary data
    """

    def __init__(self, payload: str):
        super().__init__(payload)
